using System;

namespace CyberPrism.Modules.Analytics.Models
{
    /// <summary>
    /// Sensor Data Point - Simulates real-time data generated by factory equipment
    /// </summary>
    public class SensorDataPoint
    {
        public DateTime Timestamp { get; set; }
        public string SensorId { get; set; }
        public double Value { get; set; }
        public string DataType { get; set; }  // "OEE", "Downtime", "Temperature" etc.
    }
}
